<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>vavi</groupId>
    <artifactId>vavi-nio-file-jnode</artifactId>
    <version>0.2.13</version>
  </parent>

  <artifactId>jnode-fs</artifactId>
  <packaging>jar</packaging>

  <properties>
    <vavi-net-fuse.groupId>com.github.umjammer.vavi-apps-fuse</vavi-net-fuse.groupId>
    <vavi-net-fuse.version>0.1.8</vavi-net-fuse.version>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <argLine>
            -Djava.util.logging.config.file=${project.build.testOutputDirectory}/logging.properties
          </argLine>
          <trimStackTrace>false</trimStackTrace>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <repositories>
    <repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
    </repository>
    <repository>
      <id>gitlab-maven</id> <!-- vavi-nio-file-emu -->
      <url>https://gitlab.com/api/v4/projects/31203504/packages/maven</url>
    </repository>
  </repositories>

  <dependencies>
    <dependency>
      <groupId>vavi</groupId>
      <artifactId>jnode-core</artifactId>
      <version>0.2.13</version>
    </dependency>
    <dependency>
      <!--for nfs -->
      <groupId>vavi</groupId>
      <artifactId>jnode-net</artifactId>
      <version>0.2.13</version>
    </dependency>

    <dependency>
      <groupId>com.github.umjammer</groupId>
      <artifactId>vavi-nio-file-base</artifactId>
      <version>0.0.17</version>
    </dependency>
    <dependency>
      <groupId>vavi</groupId>
      <artifactId>vavi-nio-file-emu</artifactId>
      <version>2.0.6</version>
      <exclusions>
        <exclusion>
          <groupId>com.github.umjammer</groupId>
          <artifactId>vavi-awt</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>eu.agno3.jcifs</groupId>
      <artifactId>jcifs-ng</artifactId>
      <version>2.1.10</version>
      <exclusions>
        <exclusion>
          <groupId>org.bouncycastle</groupId>
          <artifactId>bcprov-jdk18on</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
<dependency>
  <groupId>org.bouncycastle</groupId>
  <artifactId>bcprov-jdk18on</artifactId>
  <version>1.80</version>
</dependency>
    <dependency>
      <groupId>com.enterprisedt</groupId>
      <artifactId>edtFTPj</artifactId>
      <version>1.5.3</version>
    </dependency>

    <dependency>
      <groupId>com.github.umjammer</groupId> <!-- vavi / com.github.umjammer -->
      <artifactId>vavi-nio-file-qcow2</artifactId>
      <version>0.0.1</version>
    </dependency>

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-params</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.platform</groupId>
      <artifactId>junit-platform-suite-engine</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>${vavi-net-fuse.groupId}</groupId>
      <artifactId>vavi-net-fuse</artifactId>
      <version>${vavi-net-fuse.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>${vavi-net-fuse.groupId}</groupId>
      <artifactId>vavi-net-fuse</artifactId>
      <version>${vavi-net-fuse.version}</version>
      <type>test-jar</type>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-jdk14</artifactId>
      <version>1.7.36</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
